owner: tinawng
repo: Upptime
user-agent: tinawng

sites:
  # Kiko
  - name: Merge
    url: https://merge.tina.cafe/
  - name: Mellow
    url: https://mellow.tina.cafe/
  - name: Gallery
    url: https://gallery.tina.cafe/
  # Latte
  - name: 🎋 Tanabata
    url: https://tanabata.tina.cafe/ping
  - name: 🗃️ Mellow Pocketbase
    url: $MELLOW_POCKETBASE_URL
    expectedStatusCodes:
      - 404
  - name: 🗃️ Logs Pocketbase
    url: $LOGS_POCKETBASE_URL
    expectedStatusCodes:
      - 404
  # Siyu
  - name: Hello
    url: https://www.tina.cafe/
  - name: Blog
    url: https://blog.tina.cafe/
  - name: Chill
    url: https://chill.tina.cafe/
  - name: Nexon
    url: https://nexon.tina.cafe/
  - name: Baseliner
    url: https://baseliner.tina.cafe/
  - name: WatchAshFly
    url: https://watchashfly.tina.cafe/
  - name: Portal
    url: https://portal.tina.cafe/
  - name: Capture
    url: https://capture.tina.cafe/
  - name: Place
    url: https://place.tina.cafe/

# See https://upptime.js.org/docs/configuration
